import "./globals.css";
import Link from "next/link";
import ResourcesButton from "./(buttons)/resourcesbutton/page";
import GetJobAlertButton from "./(buttons)/getjobalertbutton/page";
import PostAJobButton from "./(buttons)/postajobbutton/page";

import { Nunito } from "next/font/google";

const nunito = Nunito({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.variable}`}>
        <nav className="flex gap-96">
          <div>
            <Link href="/">RemoteSG</Link>
          </div>
          <div className="flex gap-10">
            <ResourcesButton />
            <GetJobAlertButton />
            <PostAJobButton />
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
